version: "3.4"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "mozillians"
      MYSQL_PASSWORD: "mozillians"
      MYSQL_DATABASE: "moderator"
  web:
    build:
      context: .
      target: moderator-dev
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    links:
      - db
    command: ./bin/run-dev.sh
    env_file: .env
