version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "mozillians"
      MYSQL_PASSWORD: "mozillians"
      MYSQL_DATABASE: "moderator"
  web:
    build: .
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    links:
      - db
    command: ./bin/run-dev.sh
    environment:
      SECRET_KEY: "some-secret"
      DEBUG: "True"
      ANON_ALWAYS: "True"
      SESSION_COOKIE_SECURE: "False"
      DATABASE_URL: "mysql://mozillians:mozillians@db:3306/moderator"
      SITE_URL: "http://127.0.0.1:8000"
      ALLOWED_HOSTS: "127.0.0.1"
      HMAC_KEYS: >-
        {"2015-08-17": "pancakes"}
