# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mozillianprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=b'', max_length=400),
        ),
    ]
