# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 15:36


from django.conf import settings
from django.db import migrations


def forwards(apps, schema_editor):
    """Forwards method.

    Sync with mozillians.org to fix broken
    profile info.
    """
    pass


def backwards(apps, schema_editor):
    """Backwards method.

    Do nothing please.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0002_auto_20170118_1120"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
