# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def forwards(apps, schema_editor):
    """Forwards method.

    Sync with mozillians.org to fix avatar url.
    """
    pass


def backwards(apps, schema_editor):
    """Backwards method.

    Do nothing please.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0003_auto_20170118_1536"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
