# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0005_event_is_nda'),
    ]

    operations = [
        migrations.AddField(
            model_name='mozillianprofile',
            name='is_nda_member',
            field=models.BooleanField(default=False),
        ),
    ]
