# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-19 20:08


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0008_auto_20170801_0958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(
                blank=True,
                default=b"",
                validators=[django.core.validators.MaxLengthValidator(280)],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(
                validators=[
                    django.core.validators.MaxLengthValidator(280),
                    django.core.validators.MinLengthValidator(10),
                ]
            ),
        ),
    ]
