# Generated by Django 3.1.8 on 2021-05-06 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0012_auto_20210427_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(512), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(280)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(280), django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='submitter_contact_info',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
    ]
