# Generated by Django 3.1.8 on 2021-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0013_auto_20210506_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Optional: Helpful links, additional information'),
        ),
    ]
