# Generated by Django 3.1.12 on 2021-06-14 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0014_auto_20210510_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
