# Generated by Django 3.1.13 on 2022-04-26 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderate', '0015_auto_20210614_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
    ]
