# Generated by Django 4.1.11 on 2023-09-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderate", "0017_auto_20220525_0831"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_accepted",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Accepted"), (False, "Rejected"), (None, "Pending")],
                default=None,
                null=True,
            ),
        ),
    ]
