# Generated by Django 4.1.13 on 2024-02-01 14:44

from django.db import migrations, models
import moderator.moderate.models


class Migration(migrations.Migration):
    dependencies = [
        ("moderate", "0019_event_users_can_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_date",
            field=models.DateField(
                blank=True, default=moderator.moderate.models.default_date, null=True
            ),
        ),
    ]
