# Generated by Django 5.2.13 on 2026-05-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0021_alter_event_body_alter_question_question_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-event_date"]},
        ),
    ]
