# Generated by Django 5.2.13 on 2026-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0022_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mozillianprofile",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
