# Generated by Django 5.2.13 on 2026-08-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0024_backfill_is_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mozillianprofile",
            name="is_nda_member",
        ),
    ]
