# Generated by Django 5.2.13 on 2026-08-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderate", "0025_remove_mozillianprofile_is_nda_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="is_nda",
            new_name="allow_nda_community",
        ),
    ]
