name: CI Checks & Build on Fork Branches

on: [pull_request_target]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Can i haz secrets
        run: |
          env
      - name: Install dependencies
        run: |
          python -m pip install --upgrade 'pip==20.3.1'
          python -m pip install -r requirements/dev.txt
      - name: Lint with flake8
        run: flake8 moderator --count --show-source --statistics
